.. highlight:: bash
.. |project_name| replace:: ``BorgWeb``
.. |package_dirname| replace:: borgweb-|version|
.. |package_filename| replace:: |package_dirname|.tar.gz
.. |package_url| replace:: https://pypi.python.org/packages/source/b/borgweb/|package_filename|
.. |git_url| replace:: https://github.com/borgbackup/borgweb.git
.. _github: https://github.com/borgbackup/borgweb
.. _issue tracker: https://github.com/borgbackup/borgweb/issues
.. _Python: http://www.python.org/
.. _virtualenv: https://pypi.python.org/pypi/virtualenv/
.. _librelist: http://librelist.com/

